version: '3.5'
services:
    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper:5.2.1
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
        ports:
            - "2181:2181"

    broker:
        container_name: broker
        image: confluentinc/cp-kafka:5.2.1
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_MAX_REQUEST_SIZE=5210649
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
            - KAFKA_CREATE_TOPICS=topiclouzao
     
        ports:
            - "29092:29092"
            - "9092:9092"
        depends_on: 
            - zookeeper           
    
   
     
      
        
 
        
